name: blog
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  dashbook: ^0.1.4
  equatable: ^2.0.3
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.8
  font_awesome_flutter: ^9.2.0
  google_fonts: 6.2.1
  google_maps_flutter: ^2.1.0
  google_maps_flutter_web: ^0.3.2
  http: 1.2.2
  intl: ^0.19.0
  json_annotation: ^4.3.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - dotenv
