name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Dart 🎯
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies 📦
        run: dart pub get

      - name: Create Firebase Config File 🔑
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASECONFIG }}
        run: echo "$FIREBASE_CONFIG" > firebase_config.json

      - name: Build Web Assets 📦
        run: dart run build_runner build --release -o web:build/jaspr

      - name: Build Server App ⚙️
        run: dart compile exe lib/main.server.dart -o build/app -Djaspr.flags.release=true -Djaspr.dev.web=build/jaspr

      - name: Pre-render Static Pages 🏗️
        run: dart run tool/generate_static.dart

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/jaspr
          branch: gh-pages
